version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=info
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules